# Before upgrading check that everything is available on all tier1 targets here:
# https://rust-lang.github.io/rustup-components-history
[toolchain]
channel = "1.85"
components = [ "rustfmt", "clippy" ]
targets = [ "thumbv7em-none-eabi" ]
